### ISSUE TITLE
App crashes if API isn't working

### ISSUE THREAD

**Issue by WERUreo** [cforlando/PetAdoption-Android#43]
The API is not currently working correctly.  So I decided to test the Android app to see how it handles that situation...  Not well...

```
08-21 17:55:22.152 3181-3181/com.codefororlando.petadoption E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.codefororlando.petadoption, PID: 3181
                                                                              java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.Collection.toArray()' on a null object reference
                                                                                  at java.util.ArrayList.addAll(ArrayList.java:188)
                                                                                  at com.codefororlando.petadoption.fragment.FragmentListings$AnimalAdapter.setAnimals(FragmentListings.java:112)
                                                                                  at com.codefororlando.petadoption.fragment.FragmentListings$1.onResult(FragmentListings.java:55)
                                                                                  at com.codefororlando.petadoption.data.impl.PetAdoptionProvider$1.onResponse(PetAdoptionProvider.java:72)
                                                                                  at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
                                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by ToxicBakery** [comment]
Master does not crash, just blank screen. Needs notification to the user and a retry.
